resources:
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- role.yaml
- rolebinding.yaml
- deployment.yaml

images:
- name: ghcr.io/on2itsecurity/noc-k8slabels-v1
  newTag: latest
