apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
     k8s-app: noc-k8slabels-v1
  name: noc-k8slabels-v1
spec:
  podMetricsEndpoints:
  - interval: 30s
    port: prometheus
  podTargetLabels: [app]
  selector:
    matchLabels:
      app: noc-k8slabels-v1
