apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  creationTimestamp: null
  name: noc-k8slabels-lease
rules:
- apiGroups:
  - coordination.k8s.io
  resourceNames:
  - k8slabel
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - update
  - create
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - create
